### ISSUE TITLE
Very Slow on file with more than 300 lines

### ISSUE THREAD

**Issue by MilanSavaliya** [azizur/atom-wordpress-api#10]
I see it's make atom slower when this plugin is enabled and file is going to be larger than 300 lines..
It is really slow and annoying.. Plz do something about this..

**Comment by azizur** [comment]
Please provide the following information:

* Version of the Atom you are using.
* Version of the package you are using.
* List of all the other packages you are using at the same time.

If you really like to be super useful please perform a [CPU profiler with the dev tools](https://atom.io/docs/latest/hacking-atom-debugging#diagnose-performance-problems-with-the-dev-tools-cpu-profiler) and send me your result.

**Comment by MilanSavaliya** [comment]
sorry azizur. It was my problem of atom installation.. thnx for your time..
